### ISSUE TITLE
Would be nice to have an isRunning bool getter

### ISSUE THREAD

**Issue by eirikskogoy** [inf0rmatix/reliable_interval_timer#1]

**Comment by inf0rmatix** [comment]
@eirikskogoy 

That's a great idea!
 
 If you want to, you could fork the repository and implement it yourself, I'll gladly merge it and push a new release then! :)
 
 Would get you some of that sweet internet credit 💪

**Comment by inf0rmatix** [comment]
Maybe a stream would be even better, that would make reacting to any changes easier

**Comment by eirikskogoy** [comment]
Great! I will take a look😊

**Comment by eirikskogoy** [comment]
Have made a PR for a simple get isRunning. Hope this is possible to push in :)

**Comment by inf0rmatix** [comment]
yes! Will look into merging and publishing a new version this evening / tomorrow :)

**Comment by eirikskogoy** [comment]
Thanks :)

**Comment by inf0rmatix** [comment]
Hi @eirikskogoy please note that although I merged your PR,
There was an error: 
`bool get isRunning => return _isolate != null`

You can't use return in an expression body.

Since this error prevented compilation altogether, I assume that you did not even run your changed code.

To make sure your code works, always run it and try to break it.

Never just write something, hoping "it will just work" ;)

**Comment by inf0rmatix** [comment]
I also published a new version right now

**Comment by eirikskogoy** [comment]
Oh no! My bad. Sorry for that!
